export enum UserRole {
  ADMIN = 'ADMIN',
  BUYER = 'BUYER',
  CARDEALERSHIP_ADMIN = 'CARDEALERSHIP_ADMIN',
  CARDEALERSHIP_MANAGER = 'CARDEALERSHIP_MANAGER',
  CARDEALERSHIP_MECHANIC = 'CARDEALERSHIP_MECHANIC',
  CARDEALERSHIP_SALES = 'CARDEALERSHIP_SALES',
  CARDEALERSHIP_SERVICE_MANAGER = 'CARDEALERSHIP_SERVICE_MANAGER',
  MANAGER = 'MANAGER',
  SELLER = 'SELLER',
  SELLER_PREMIUM = 'SELLER_PREMIUM',
}
